services:
  app_database:
    image: postgres:18
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d app_db -h localhost -p 5432" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - pgdata:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"

  app_goma:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      app_database:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg://${DB_USER}:${DB_PASSWORD}@app_database:5432/app_db

volumes:
  pgdata:
