"""delete user on cascade on friendship

Revision ID: 800ba087fa56
Revises: 82cc840c58f9
Create Date: 2026-03-27 08:20:44.081935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '800ba087fa56'
down_revision: Union[str, Sequence[str], None] = '82cc840c58f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friendship', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_friendship_blocked_by_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_friendship_requested_by_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_friendship_user_id1_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_friendship_user_id2_user'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_friendship_user_id2_user'), 'user', ['user_id2'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_friendship_requested_by_user'), 'user', ['requested_by'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_friendship_user_id1_user'), 'user', ['user_id1'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_friendship_blocked_by_user'), 'user', ['blocked_by'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('friendship', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_friendship_blocked_by_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_friendship_user_id1_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_friendship_requested_by_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_friendship_user_id2_user'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_friendship_user_id2_user'), 'user', ['user_id2'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_friendship_user_id1_user'), 'user', ['user_id1'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_friendship_requested_by_user'), 'user', ['requested_by'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_friendship_blocked_by_user'), 'user', ['blocked_by'], ['id'])

    # ### end Alembic commands ###
