"""add field block_by at friendshio table

Revision ID: 82cc840c58f9
Revises: e1780c25080c
Create Date: 2026-02-27 19:25:16.339434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '82cc840c58f9'
down_revision: Union[str, Sequence[str], None] = 'e1780c25080c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_friendship')
    with op.batch_alter_table('friendship', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blocked_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_friendship_blocked_by_user'), 'user', ['blocked_by'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friendship', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_friendship_blocked_by_user'), type_='foreignkey')
        batch_op.drop_column('blocked_by')

    op.create_table('_alembic_tmp_friendship',
    sa.Column('status', sa.VARCHAR(length=8), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('user_id1', sa.INTEGER(), nullable=False),
    sa.Column('user_id2', sa.INTEGER(), nullable=False),
    sa.Column('requested_by', sa.INTEGER(), nullable=False),
    sa.Column('blocked_by', sa.INTEGER(), nullable=False),
    sa.CheckConstraint('user_id1 < user_id2', name=op.f('ck_friendship_check_ordered_ids')),
    sa.ForeignKeyConstraint(['blocked_by'], ['user.id'], name=op.f('fk_friendship_blocked_by_user')),
    sa.ForeignKeyConstraint(['requested_by'], ['user.id'], name=op.f('fk_friendship_requested_by_user')),
    sa.ForeignKeyConstraint(['user_id1'], ['user.id'], name=op.f('fk_friendship_user_id1_user')),
    sa.ForeignKeyConstraint(['user_id2'], ['user.id'], name=op.f('fk_friendship_user_id2_user'))
    )
    # ### end Alembic commands ###
