"""create friendship

Revision ID: 92e3783a29f6
Revises: e1e9b891a485
Create Date: 2026-02-22 19:26:28.193419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '92e3783a29f6'
down_revision: Union[str, Sequence[str], None] = 'e1e9b891a485'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendship',
    sa.Column('user_id_1', sa.Integer(), nullable=False),
    sa.Column('user_id_2', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'BLOCKED', name='friendstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id_1'], ['user.id'], name=op.f('fk_friendship_user_id_1_user')),
    sa.ForeignKeyConstraint(['user_id_2'], ['user.id'], name=op.f('fk_friendship_user_id_2_user')),
    sa.PrimaryKeyConstraint('user_id_1', 'user_id_2', name=op.f('pk_friendship'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friendship')
    # ### end Alembic commands ###
