"""add constraint to check ordered id to friendship

Revision ID: a5ee7d2ec5cf
Revises: 92e3783a29f6
Create Date: 2026-02-26 20:31:17.709335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a5ee7d2ec5cf'
down_revision: Union[str, Sequence[str], None] = '92e3783a29f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friendship', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id1', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('user_id2', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_friendship_user_id_2_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_friendship_user_id_1_user'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_friendship_user_id1_user'), 'user', ['user_id1'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_friendship_user_id2_user'), 'user', ['user_id2'], ['id'])
        batch_op.create_check_constraint('check_ordered_ids', 'user_id1 < user_id2')
        batch_op.drop_column('user_id_2')
        batch_op.drop_column('user_id_1')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friendship', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id_1', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('user_id_2', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_friendship_user_id2_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_friendship_user_id1_user'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_friendship_user_id_1_user'), 'user', ['user_id_1'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_friendship_user_id_2_user'), 'user', ['user_id_2'], ['id'])
        batch_op.drop_constraint(
            "check_ordered_ids",
            type_="check"
        )
        batch_op.drop_column('user_id2')
        batch_op.drop_column('user_id1')

    # ### end Alembic commands ###
