"""adiciona request_by na friendship

Revision ID: e1780c25080c
Revises: a5ee7d2ec5cf
Create Date: 2026-02-26 22:43:37.963953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e1780c25080c'
down_revision: Union[str, Sequence[str], None] = 'a5ee7d2ec5cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friendship', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requested_by', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_friendship_requested_by'), ['requested_by'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_friendship_requested_by_user'), 'user', ['requested_by'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friendship', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_friendship_requested_by_user'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_friendship_requested_by'))
        batch_op.drop_column('requested_by')

    # ### end Alembic commands ###
